# Generated by Django 4.1.4 on 2023-01-09 17:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('numero', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Animais',
                'ordering': ('numero', 'nome'),
            },
        ),
        migrations.CreateModel(
            name='Sorteios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_do_sorteio', models.DateField(auto_now=True)),
                ('hora_do_sorteio', models.TimeField(auto_now_add=True)),
                ('bixo_sorteado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bixoapp.animais')),
            ],
            options={
                'verbose_name': 'Sorteio',
            },
        ),
        migrations.CreateModel(
            name='ApostasTerno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_da_aposta', models.DateField(auto_now=True)),
                ('hora_da_aposta', models.TimeField(auto_now_add=True)),
                ('valor_apostado', models.FloatField(default=15, validators=[django.core.validators.MinValueValidator(15)])),
                ('primeiro_num_apostado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primeiro_terno', to='bixoapp.animais')),
                ('segundo_num_apostado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segundo_terno', to='bixoapp.animais')),
                ('terceiro_num_apostado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terceiro_terno', to='bixoapp.animais')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Terno',
            },
        ),
        migrations.CreateModel(
            name='ApostasQuina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_da_aposta', models.DateField(auto_now=True)),
                ('hora_da_aposta', models.TimeField(auto_now_add=True)),
                ('valor_apostado', models.FloatField(default=25, validators=[django.core.validators.MinValueValidator(25)])),
                ('primeiro_num_apostado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primeiro_quina', to='bixoapp.animais')),
                ('quarto_num_apostado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarto_quina', to='bixoapp.animais')),
                ('quinto_num_apostado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quinto_quina', to='bixoapp.animais')),
                ('segundo_num_apostado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segundo_quina', to='bixoapp.animais')),
                ('terceiro_num_apostado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terceiro_quina', to='bixoapp.animais')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quina',
            },
        ),
        migrations.CreateModel(
            name='ApostasQuadra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_da_aposta', models.DateField(auto_now=True)),
                ('hora_da_aposta', models.TimeField(auto_now_add=True)),
                ('valor_apostado', models.FloatField(default=20, validators=[django.core.validators.MinValueValidator(20)])),
                ('primeiro_num_apostado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primeiro_quadra', to='bixoapp.animais')),
                ('quarto_num_apostado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarto_quadra', to='bixoapp.animais')),
                ('segundo_num_apostado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segundo_quadra', to='bixoapp.animais')),
                ('terceiro_num_apostado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terceiro_quadra', to='bixoapp.animais')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quadra',
            },
        ),
        migrations.CreateModel(
            name='ApostasGrupo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_da_aposta', models.DateField(auto_now=True)),
                ('hora_da_aposta', models.TimeField(auto_now_add=True)),
                ('valor_apostado', models.FloatField(default=1)),
                ('bixo_apostado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bixoapp.animais')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grupo',
            },
        ),
        migrations.CreateModel(
            name='ApostasDuque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_da_aposta', models.DateField(auto_now=True)),
                ('hora_da_aposta', models.TimeField(auto_now_add=True)),
                ('valor_apostado', models.FloatField(default=10, validators=[django.core.validators.MinValueValidator(10)])),
                ('primeiro_num_apostado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primeiro_duque', to='bixoapp.animais')),
                ('segundo_num_apostado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segundo_duque', to='bixoapp.animais')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Duque',
            },
        ),
    ]
