# Generated by Django 4.1.4 on 2023-01-14 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bixoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorteios',
            name='sorteio_do_dia',
            field=models.IntegerField(default=25, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
