# Generated by Django 4.1.4 on 2023-01-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bixoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apostasduque',
            name='data_da_aposta',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='apostasgrupo',
            name='data_da_aposta',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='apostasquadra',
            name='data_da_aposta',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='apostasquina',
            name='data_da_aposta',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='apostasterno',
            name='data_da_aposta',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sorteios',
            name='data_do_sorteio',
            field=models.DateField(auto_now=True),
        ),
    ]
