# Generated by Django 4.1.4 on 2023-01-14 20:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bixoapp', '0002_sorteios_sorteio_do_dia'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomFrases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='sorteios',
            name='sorteio_do_dia',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
