# Generated by Django 4.1.4 on 2023-01-05 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bixoapp', '0002_alter_apostasduque_data_da_aposta_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animais',
            options={'ordering': ('numero', 'nome'), 'verbose_name_plural': 'Animais'},
        ),
    ]
